//
// Copyright (c) ZeroC, Inc. All rights reserved.
//
//
// Ice version 3.7.5
//
// <auto-generated>
//
// Generated from file `Notification.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package Notification;

/** @hidden */
public class _NotifierPrxI extends com.zeroc.Ice._ObjectPrxI implements NotifierPrx
{
    /** @hidden */
    public static final long serialVersionUID = 0L;
}
