//
// Copyright (c) ZeroC, Inc. All rights reserved.
//
//
// Ice version 3.7.5
//
// <auto-generated>
//
// Generated from file `Notification.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package Notification;

/**
 * Helper class for marshaling/unmarshaling batchedResults.
 **/
public final class batchedResultsHelper
{
    public static void write(com.zeroc.Ice.OutputStream ostr, caseResult[] v)
    {
        if(v == null)
        {
            ostr.writeSize(0);
        }
        else
        {
            ostr.writeSize(v.length);
            for(int i0 = 0; i0 < v.length; i0++)
            {
                caseResult.ice_write(ostr, v[i0]);
            }
        }
    }

    public static caseResult[] read(com.zeroc.Ice.InputStream istr)
    {
        final caseResult[] v;
        final int len0 = istr.readAndCheckSeqSize(17);
        v = new caseResult[len0];
        for(int i0 = 0; i0 < len0; i0++)
        {
            v[i0] = caseResult.ice_read(istr);
        }
        return v;
    }

    public static void write(com.zeroc.Ice.OutputStream ostr, int tag, java.util.Optional<caseResult[]> v)
    {
        if(v != null && v.isPresent())
        {
            write(ostr, tag, v.get());
        }
    }

    public static void write(com.zeroc.Ice.OutputStream ostr, int tag, caseResult[] v)
    {
        if(ostr.writeOptional(tag, com.zeroc.Ice.OptionalFormat.FSize))
        {
            int pos = ostr.startSize();
            batchedResultsHelper.write(ostr, v);
            ostr.endSize(pos);
        }
    }

    public static java.util.Optional<caseResult[]> read(com.zeroc.Ice.InputStream istr, int tag)
    {
        if(istr.readOptional(tag, com.zeroc.Ice.OptionalFormat.FSize))
        {
            istr.skip(4);
            caseResult[] v;
            v = batchedResultsHelper.read(istr);
            return java.util.Optional.of(v);
        }
        else
        {
            return java.util.Optional.empty();
        }
    }
}
