//
// Copyright (c) ZeroC, Inc. All rights reserved.
//
//
// Ice version 3.7.5
//
// <auto-generated>
//
// Generated from file `Notification.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package Notification;

public class timeStamp implements java.lang.Cloneable,
                                  java.io.Serializable
{
    public int hour;

    public int minute;

    public int second;

    public timeStamp()
    {
    }

    public timeStamp(int hour, int minute, int second)
    {
        this.hour = hour;
        this.minute = minute;
        this.second = second;
    }

    public boolean equals(java.lang.Object rhs)
    {
        if(this == rhs)
        {
            return true;
        }
        timeStamp r = null;
        if(rhs instanceof timeStamp)
        {
            r = (timeStamp)rhs;
        }

        if(r != null)
        {
            if(this.hour != r.hour)
            {
                return false;
            }
            if(this.minute != r.minute)
            {
                return false;
            }
            if(this.second != r.second)
            {
                return false;
            }

            return true;
        }

        return false;
    }

    public int hashCode()
    {
        int h_ = 5381;
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, "::Notification::timeStamp");
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, hour);
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, minute);
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, second);
        return h_;
    }

    public timeStamp clone()
    {
        timeStamp c = null;
        try
        {
            c = (timeStamp)super.clone();
        }
        catch(CloneNotSupportedException ex)
        {
            assert false; // impossible
        }
        return c;
    }

    public void ice_writeMembers(com.zeroc.Ice.OutputStream ostr)
    {
        ostr.writeInt(this.hour);
        ostr.writeInt(this.minute);
        ostr.writeInt(this.second);
    }

    public void ice_readMembers(com.zeroc.Ice.InputStream istr)
    {
        this.hour = istr.readInt();
        this.minute = istr.readInt();
        this.second = istr.readInt();
    }

    static public void ice_write(com.zeroc.Ice.OutputStream ostr, timeStamp v)
    {
        if(v == null)
        {
            _nullMarshalValue.ice_writeMembers(ostr);
        }
        else
        {
            v.ice_writeMembers(ostr);
        }
    }

    static public timeStamp ice_read(com.zeroc.Ice.InputStream istr)
    {
        timeStamp v = new timeStamp();
        v.ice_readMembers(istr);
        return v;
    }

    static public void ice_write(com.zeroc.Ice.OutputStream ostr, int tag, java.util.Optional<timeStamp> v)
    {
        if(v != null && v.isPresent())
        {
            ice_write(ostr, tag, v.get());
        }
    }

    static public void ice_write(com.zeroc.Ice.OutputStream ostr, int tag, timeStamp v)
    {
        if(ostr.writeOptional(tag, com.zeroc.Ice.OptionalFormat.VSize))
        {
            ostr.writeSize(12);
            ice_write(ostr, v);
        }
    }

    static public java.util.Optional<timeStamp> ice_read(com.zeroc.Ice.InputStream istr, int tag)
    {
        if(istr.readOptional(tag, com.zeroc.Ice.OptionalFormat.VSize))
        {
            istr.skipSize();
            return java.util.Optional.of(timeStamp.ice_read(istr));
        }
        else
        {
            return java.util.Optional.empty();
        }
    }

    private static final timeStamp _nullMarshalValue = new timeStamp();

    /** @hidden */
    public static final long serialVersionUID = -1724861903L;
}
