// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: letterformatting.proto

package letterFormatting;

public interface LetterFormatRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:letterFormatting.LetterFormatRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>bool toUpper = 1;</code>
   * @return The toUpper.
   */
  boolean getToUpper();

  /**
   * <code>string text = 2;</code>
   * @return The text.
   */
  java.lang.String getText();
  /**
   * <code>string text = 2;</code>
   * @return The bytes for text.
   */
  com.google.protobuf.ByteString
      getTextBytes();
}
