//
// Copyright (c) ZeroC, Inc. All rights reserved.
//
//
// Ice version 3.7.5
//
// <auto-generated>
//
// Generated from file `Office.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package Office;

public interface ServicePrx extends com.zeroc.Ice.ObjectPrx
{
    default int requestUnemployedAid(basicCaseData data, float averageEarnings)
    {
        return requestUnemployedAid(data, averageEarnings, com.zeroc.Ice.ObjectPrx.noExplicitContext);
    }

    default int requestUnemployedAid(basicCaseData data, float averageEarnings, java.util.Map<String, String> context)
    {
        return _iceI_requestUnemployedAidAsync(data, averageEarnings, context, true).waitForResponse();
    }

    default java.util.concurrent.CompletableFuture<java.lang.Integer> requestUnemployedAidAsync(basicCaseData data, float averageEarnings)
    {
        return _iceI_requestUnemployedAidAsync(data, averageEarnings, com.zeroc.Ice.ObjectPrx.noExplicitContext, false);
    }

    default java.util.concurrent.CompletableFuture<java.lang.Integer> requestUnemployedAidAsync(basicCaseData data, float averageEarnings, java.util.Map<String, String> context)
    {
        return _iceI_requestUnemployedAidAsync(data, averageEarnings, context, false);
    }

    /**
     * @hidden
     * @param iceP_data -
     * @param iceP_averageEarnings -
     * @param context -
     * @param sync -
     * @return -
     **/
    default com.zeroc.IceInternal.OutgoingAsync<java.lang.Integer> _iceI_requestUnemployedAidAsync(basicCaseData iceP_data, float iceP_averageEarnings, java.util.Map<String, String> context, boolean sync)
    {
        com.zeroc.IceInternal.OutgoingAsync<java.lang.Integer> f = new com.zeroc.IceInternal.OutgoingAsync<>(this, "requestUnemployedAid", null, sync, null);
        f.invoke(true, context, null, ostr -> {
                     basicCaseData.ice_write(ostr, iceP_data);
                     ostr.writeFloat(iceP_averageEarnings);
                 }, istr -> {
                     int ret;
                     ret = istr.readInt();
                     return ret;
                 });
        return f;
    }

    default int requestBuildingPermission(basicCaseData data, String address, float area)
    {
        return requestBuildingPermission(data, address, area, com.zeroc.Ice.ObjectPrx.noExplicitContext);
    }

    default int requestBuildingPermission(basicCaseData data, String address, float area, java.util.Map<String, String> context)
    {
        return _iceI_requestBuildingPermissionAsync(data, address, area, context, true).waitForResponse();
    }

    default java.util.concurrent.CompletableFuture<java.lang.Integer> requestBuildingPermissionAsync(basicCaseData data, String address, float area)
    {
        return _iceI_requestBuildingPermissionAsync(data, address, area, com.zeroc.Ice.ObjectPrx.noExplicitContext, false);
    }

    default java.util.concurrent.CompletableFuture<java.lang.Integer> requestBuildingPermissionAsync(basicCaseData data, String address, float area, java.util.Map<String, String> context)
    {
        return _iceI_requestBuildingPermissionAsync(data, address, area, context, false);
    }

    /**
     * @hidden
     * @param iceP_data -
     * @param iceP_address -
     * @param iceP_area -
     * @param context -
     * @param sync -
     * @return -
     **/
    default com.zeroc.IceInternal.OutgoingAsync<java.lang.Integer> _iceI_requestBuildingPermissionAsync(basicCaseData iceP_data, String iceP_address, float iceP_area, java.util.Map<String, String> context, boolean sync)
    {
        com.zeroc.IceInternal.OutgoingAsync<java.lang.Integer> f = new com.zeroc.IceInternal.OutgoingAsync<>(this, "requestBuildingPermission", null, sync, null);
        f.invoke(true, context, null, ostr -> {
                     basicCaseData.ice_write(ostr, iceP_data);
                     ostr.writeString(iceP_address);
                     ostr.writeFloat(iceP_area);
                 }, istr -> {
                     int ret;
                     ret = istr.readInt();
                     return ret;
                 });
        return f;
    }

    default int requestDrivingLicence(basicCaseData data, long candidateProfile, boolean isFirstLicence)
    {
        return requestDrivingLicence(data, candidateProfile, isFirstLicence, com.zeroc.Ice.ObjectPrx.noExplicitContext);
    }

    default int requestDrivingLicence(basicCaseData data, long candidateProfile, boolean isFirstLicence, java.util.Map<String, String> context)
    {
        return _iceI_requestDrivingLicenceAsync(data, candidateProfile, isFirstLicence, context, true).waitForResponse();
    }

    default java.util.concurrent.CompletableFuture<java.lang.Integer> requestDrivingLicenceAsync(basicCaseData data, long candidateProfile, boolean isFirstLicence)
    {
        return _iceI_requestDrivingLicenceAsync(data, candidateProfile, isFirstLicence, com.zeroc.Ice.ObjectPrx.noExplicitContext, false);
    }

    default java.util.concurrent.CompletableFuture<java.lang.Integer> requestDrivingLicenceAsync(basicCaseData data, long candidateProfile, boolean isFirstLicence, java.util.Map<String, String> context)
    {
        return _iceI_requestDrivingLicenceAsync(data, candidateProfile, isFirstLicence, context, false);
    }

    /**
     * @hidden
     * @param iceP_data -
     * @param iceP_candidateProfile -
     * @param iceP_isFirstLicence -
     * @param context -
     * @param sync -
     * @return -
     **/
    default com.zeroc.IceInternal.OutgoingAsync<java.lang.Integer> _iceI_requestDrivingLicenceAsync(basicCaseData iceP_data, long iceP_candidateProfile, boolean iceP_isFirstLicence, java.util.Map<String, String> context, boolean sync)
    {
        com.zeroc.IceInternal.OutgoingAsync<java.lang.Integer> f = new com.zeroc.IceInternal.OutgoingAsync<>(this, "requestDrivingLicence", null, sync, null);
        f.invoke(true, context, null, ostr -> {
                     basicCaseData.ice_write(ostr, iceP_data);
                     ostr.writeLong(iceP_candidateProfile);
                     ostr.writeBool(iceP_isFirstLicence);
                 }, istr -> {
                     int ret;
                     ret = istr.readInt();
                     return ret;
                 });
        return f;
    }

    /**
     * Contacts the remote server to verify that the object implements this type.
     * Raises a local exception if a communication error occurs.
     * @param obj The untyped proxy.
     * @return A proxy for this type, or null if the object does not support this type.
     **/
    static ServicePrx checkedCast(com.zeroc.Ice.ObjectPrx obj)
    {
        return com.zeroc.Ice.ObjectPrx._checkedCast(obj, ice_staticId(), ServicePrx.class, _ServicePrxI.class);
    }

    /**
     * Contacts the remote server to verify that the object implements this type.
     * Raises a local exception if a communication error occurs.
     * @param obj The untyped proxy.
     * @param context The Context map to send with the invocation.
     * @return A proxy for this type, or null if the object does not support this type.
     **/
    static ServicePrx checkedCast(com.zeroc.Ice.ObjectPrx obj, java.util.Map<String, String> context)
    {
        return com.zeroc.Ice.ObjectPrx._checkedCast(obj, context, ice_staticId(), ServicePrx.class, _ServicePrxI.class);
    }

    /**
     * Contacts the remote server to verify that a facet of the object implements this type.
     * Raises a local exception if a communication error occurs.
     * @param obj The untyped proxy.
     * @param facet The name of the desired facet.
     * @return A proxy for this type, or null if the object does not support this type.
     **/
    static ServicePrx checkedCast(com.zeroc.Ice.ObjectPrx obj, String facet)
    {
        return com.zeroc.Ice.ObjectPrx._checkedCast(obj, facet, ice_staticId(), ServicePrx.class, _ServicePrxI.class);
    }

    /**
     * Contacts the remote server to verify that a facet of the object implements this type.
     * Raises a local exception if a communication error occurs.
     * @param obj The untyped proxy.
     * @param facet The name of the desired facet.
     * @param context The Context map to send with the invocation.
     * @return A proxy for this type, or null if the object does not support this type.
     **/
    static ServicePrx checkedCast(com.zeroc.Ice.ObjectPrx obj, String facet, java.util.Map<String, String> context)
    {
        return com.zeroc.Ice.ObjectPrx._checkedCast(obj, facet, context, ice_staticId(), ServicePrx.class, _ServicePrxI.class);
    }

    /**
     * Downcasts the given proxy to this type without contacting the remote server.
     * @param obj The untyped proxy.
     * @return A proxy for this type.
     **/
    static ServicePrx uncheckedCast(com.zeroc.Ice.ObjectPrx obj)
    {
        return com.zeroc.Ice.ObjectPrx._uncheckedCast(obj, ServicePrx.class, _ServicePrxI.class);
    }

    /**
     * Downcasts the given proxy to this type without contacting the remote server.
     * @param obj The untyped proxy.
     * @param facet The name of the desired facet.
     * @return A proxy for this type.
     **/
    static ServicePrx uncheckedCast(com.zeroc.Ice.ObjectPrx obj, String facet)
    {
        return com.zeroc.Ice.ObjectPrx._uncheckedCast(obj, facet, ServicePrx.class, _ServicePrxI.class);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the per-proxy context.
     * @param newContext The context for the new proxy.
     * @return A proxy with the specified per-proxy context.
     **/
    @Override
    default ServicePrx ice_context(java.util.Map<String, String> newContext)
    {
        return (ServicePrx)_ice_context(newContext);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the adapter ID.
     * @param newAdapterId The adapter ID for the new proxy.
     * @return A proxy with the specified adapter ID.
     **/
    @Override
    default ServicePrx ice_adapterId(String newAdapterId)
    {
        return (ServicePrx)_ice_adapterId(newAdapterId);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the endpoints.
     * @param newEndpoints The endpoints for the new proxy.
     * @return A proxy with the specified endpoints.
     **/
    @Override
    default ServicePrx ice_endpoints(com.zeroc.Ice.Endpoint[] newEndpoints)
    {
        return (ServicePrx)_ice_endpoints(newEndpoints);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the locator cache timeout.
     * @param newTimeout The new locator cache timeout (in seconds).
     * @return A proxy with the specified locator cache timeout.
     **/
    @Override
    default ServicePrx ice_locatorCacheTimeout(int newTimeout)
    {
        return (ServicePrx)_ice_locatorCacheTimeout(newTimeout);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the invocation timeout.
     * @param newTimeout The new invocation timeout (in seconds).
     * @return A proxy with the specified invocation timeout.
     **/
    @Override
    default ServicePrx ice_invocationTimeout(int newTimeout)
    {
        return (ServicePrx)_ice_invocationTimeout(newTimeout);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for connection caching.
     * @param newCache <code>true</code> if the new proxy should cache connections; <code>false</code> otherwise.
     * @return A proxy with the specified caching policy.
     **/
    @Override
    default ServicePrx ice_connectionCached(boolean newCache)
    {
        return (ServicePrx)_ice_connectionCached(newCache);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the endpoint selection policy.
     * @param newType The new endpoint selection policy.
     * @return A proxy with the specified endpoint selection policy.
     **/
    @Override
    default ServicePrx ice_endpointSelection(com.zeroc.Ice.EndpointSelectionType newType)
    {
        return (ServicePrx)_ice_endpointSelection(newType);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for how it selects endpoints.
     * @param b If <code>b</code> is <code>true</code>, only endpoints that use a secure transport are
     * used by the new proxy. If <code>b</code> is false, the returned proxy uses both secure and
     * insecure endpoints.
     * @return A proxy with the specified selection policy.
     **/
    @Override
    default ServicePrx ice_secure(boolean b)
    {
        return (ServicePrx)_ice_secure(b);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the encoding used to marshal parameters.
     * @param e The encoding version to use to marshal request parameters.
     * @return A proxy with the specified encoding version.
     **/
    @Override
    default ServicePrx ice_encodingVersion(com.zeroc.Ice.EncodingVersion e)
    {
        return (ServicePrx)_ice_encodingVersion(e);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for its endpoint selection policy.
     * @param b If <code>b</code> is <code>true</code>, the new proxy will use secure endpoints for invocations
     * and only use insecure endpoints if an invocation cannot be made via secure endpoints. If <code>b</code> is
     * <code>false</code>, the proxy prefers insecure endpoints to secure ones.
     * @return A proxy with the specified selection policy.
     **/
    @Override
    default ServicePrx ice_preferSecure(boolean b)
    {
        return (ServicePrx)_ice_preferSecure(b);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the router.
     * @param router The router for the new proxy.
     * @return A proxy with the specified router.
     **/
    @Override
    default ServicePrx ice_router(com.zeroc.Ice.RouterPrx router)
    {
        return (ServicePrx)_ice_router(router);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the locator.
     * @param locator The locator for the new proxy.
     * @return A proxy with the specified locator.
     **/
    @Override
    default ServicePrx ice_locator(com.zeroc.Ice.LocatorPrx locator)
    {
        return (ServicePrx)_ice_locator(locator);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for collocation optimization.
     * @param b <code>true</code> if the new proxy enables collocation optimization; <code>false</code> otherwise.
     * @return A proxy with the specified collocation optimization.
     **/
    @Override
    default ServicePrx ice_collocationOptimized(boolean b)
    {
        return (ServicePrx)_ice_collocationOptimized(b);
    }

    /**
     * Returns a proxy that is identical to this proxy, but uses twoway invocations.
     * @return A proxy that uses twoway invocations.
     **/
    @Override
    default ServicePrx ice_twoway()
    {
        return (ServicePrx)_ice_twoway();
    }

    /**
     * Returns a proxy that is identical to this proxy, but uses oneway invocations.
     * @return A proxy that uses oneway invocations.
     **/
    @Override
    default ServicePrx ice_oneway()
    {
        return (ServicePrx)_ice_oneway();
    }

    /**
     * Returns a proxy that is identical to this proxy, but uses batch oneway invocations.
     * @return A proxy that uses batch oneway invocations.
     **/
    @Override
    default ServicePrx ice_batchOneway()
    {
        return (ServicePrx)_ice_batchOneway();
    }

    /**
     * Returns a proxy that is identical to this proxy, but uses datagram invocations.
     * @return A proxy that uses datagram invocations.
     **/
    @Override
    default ServicePrx ice_datagram()
    {
        return (ServicePrx)_ice_datagram();
    }

    /**
     * Returns a proxy that is identical to this proxy, but uses batch datagram invocations.
     * @return A proxy that uses batch datagram invocations.
     **/
    @Override
    default ServicePrx ice_batchDatagram()
    {
        return (ServicePrx)_ice_batchDatagram();
    }

    /**
     * Returns a proxy that is identical to this proxy, except for compression.
     * @param co <code>true</code> enables compression for the new proxy; <code>false</code> disables compression.
     * @return A proxy with the specified compression setting.
     **/
    @Override
    default ServicePrx ice_compress(boolean co)
    {
        return (ServicePrx)_ice_compress(co);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for its connection timeout setting.
     * @param t The connection timeout for the proxy in milliseconds.
     * @return A proxy with the specified timeout.
     **/
    @Override
    default ServicePrx ice_timeout(int t)
    {
        return (ServicePrx)_ice_timeout(t);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for its connection ID.
     * @param connectionId The connection ID for the new proxy. An empty string removes the connection ID.
     * @return A proxy with the specified connection ID.
     **/
    @Override
    default ServicePrx ice_connectionId(String connectionId)
    {
        return (ServicePrx)_ice_connectionId(connectionId);
    }

    /**
     * Returns a proxy that is identical to this proxy, except it's a fixed proxy bound
     * the given connection.@param connection The fixed proxy connection.
     * @return A fixed proxy bound to the given connection.
     **/
    @Override
    default ServicePrx ice_fixed(com.zeroc.Ice.Connection connection)
    {
        return (ServicePrx)_ice_fixed(connection);
    }

    static String ice_staticId()
    {
        return "::Office::Service";
    }
}
