//
// Copyright (c) ZeroC, Inc. All rights reserved.
//
//
// Ice version 3.7.5
//
// <auto-generated>
//
// Generated from file `HelperTypes.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package HelperTypes;

/**
 * Helper class for marshaling/unmarshaling DictSeq.
 **/
public final class DictSeqHelper
{
    public static void write(com.zeroc.Ice.OutputStream ostr, java.util.Map<java.lang.String, java.lang.Integer>[] v)
    {
        if(v == null)
        {
            ostr.writeSize(0);
        }
        else
        {
            ostr.writeSize(v.length);
            for(int i0 = 0; i0 < v.length; i0++)
            {
                StrToIntDictHelper.write(ostr, v[i0]);
            }
        }
    }

    @SuppressWarnings("unchecked")
    public static java.util.Map<java.lang.String, java.lang.Integer>[] read(com.zeroc.Ice.InputStream istr)
    {
        final java.util.Map<java.lang.String, java.lang.Integer>[] v;
        final int len0 = istr.readAndCheckSeqSize(1);
        v = (java.util.Map<java.lang.String, java.lang.Integer>[])new java.util.Map[len0];
        for(int i0 = 0; i0 < len0; i0++)
        {
            v[i0] = StrToIntDictHelper.read(istr);
        }
        return v;
    }

    public static void write(com.zeroc.Ice.OutputStream ostr, int tag, java.util.Optional<java.util.Map<java.lang.String, java.lang.Integer>[]> v)
    {
        if(v != null && v.isPresent())
        {
            write(ostr, tag, v.get());
        }
    }

    public static void write(com.zeroc.Ice.OutputStream ostr, int tag, java.util.Map<java.lang.String, java.lang.Integer>[] v)
    {
        if(ostr.writeOptional(tag, com.zeroc.Ice.OptionalFormat.FSize))
        {
            int pos = ostr.startSize();
            DictSeqHelper.write(ostr, v);
            ostr.endSize(pos);
        }
    }

    public static java.util.Optional<java.util.Map<java.lang.String, java.lang.Integer>[]> read(com.zeroc.Ice.InputStream istr, int tag)
    {
        if(istr.readOptional(tag, com.zeroc.Ice.OptionalFormat.FSize))
        {
            istr.skip(4);
            java.util.Map<java.lang.String, java.lang.Integer>[] v;
            v = DictSeqHelper.read(istr);
            return java.util.Optional.of(v);
        }
        else
        {
            return java.util.Optional.empty();
        }
    }
}
