// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: randomstreaming.proto

package randomStreaming;

public interface NextRandomOrBuilder extends
    // @@protoc_insertion_point(interface_extends:randomStreaming.NextRandom)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 next = 1;</code>
   * @return The next.
   */
  int getNext();
}
