// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: randomstreaming.proto

package randomStreaming;

/**
 * Protobuf type {@code randomStreaming.RandomStreamRequest}
 */
public final class RandomStreamRequest extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:randomStreaming.RandomStreamRequest)
    RandomStreamRequestOrBuilder {
private static final long serialVersionUID = 0L;
  // Use RandomStreamRequest.newBuilder() to construct.
  private RandomStreamRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private RandomStreamRequest() {
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new RandomStreamRequest();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private RandomStreamRequest(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 8: {

            bound_ = input.readInt32();
            break;
          }
          case 16: {

            count_ = input.readInt32();
            break;
          }
          case 24: {

            timeInterval_ = input.readInt32();
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return randomStreaming.RandomStreamingProto.internal_static_randomStreaming_RandomStreamRequest_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return randomStreaming.RandomStreamingProto.internal_static_randomStreaming_RandomStreamRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            randomStreaming.RandomStreamRequest.class, randomStreaming.RandomStreamRequest.Builder.class);
  }

  public static final int BOUND_FIELD_NUMBER = 1;
  private int bound_;
  /**
   * <code>int32 bound = 1;</code>
   * @return The bound.
   */
  @java.lang.Override
  public int getBound() {
    return bound_;
  }

  public static final int COUNT_FIELD_NUMBER = 2;
  private int count_;
  /**
   * <code>int32 count = 2;</code>
   * @return The count.
   */
  @java.lang.Override
  public int getCount() {
    return count_;
  }

  public static final int TIME_INTERVAL_FIELD_NUMBER = 3;
  private int timeInterval_;
  /**
   * <code>int32 time_interval = 3;</code>
   * @return The timeInterval.
   */
  @java.lang.Override
  public int getTimeInterval() {
    return timeInterval_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (bound_ != 0) {
      output.writeInt32(1, bound_);
    }
    if (count_ != 0) {
      output.writeInt32(2, count_);
    }
    if (timeInterval_ != 0) {
      output.writeInt32(3, timeInterval_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (bound_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(1, bound_);
    }
    if (count_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(2, count_);
    }
    if (timeInterval_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(3, timeInterval_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof randomStreaming.RandomStreamRequest)) {
      return super.equals(obj);
    }
    randomStreaming.RandomStreamRequest other = (randomStreaming.RandomStreamRequest) obj;

    if (getBound()
        != other.getBound()) return false;
    if (getCount()
        != other.getCount()) return false;
    if (getTimeInterval()
        != other.getTimeInterval()) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + BOUND_FIELD_NUMBER;
    hash = (53 * hash) + getBound();
    hash = (37 * hash) + COUNT_FIELD_NUMBER;
    hash = (53 * hash) + getCount();
    hash = (37 * hash) + TIME_INTERVAL_FIELD_NUMBER;
    hash = (53 * hash) + getTimeInterval();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static randomStreaming.RandomStreamRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static randomStreaming.RandomStreamRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static randomStreaming.RandomStreamRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static randomStreaming.RandomStreamRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static randomStreaming.RandomStreamRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static randomStreaming.RandomStreamRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static randomStreaming.RandomStreamRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static randomStreaming.RandomStreamRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static randomStreaming.RandomStreamRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static randomStreaming.RandomStreamRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static randomStreaming.RandomStreamRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static randomStreaming.RandomStreamRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(randomStreaming.RandomStreamRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code randomStreaming.RandomStreamRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:randomStreaming.RandomStreamRequest)
      randomStreaming.RandomStreamRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return randomStreaming.RandomStreamingProto.internal_static_randomStreaming_RandomStreamRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return randomStreaming.RandomStreamingProto.internal_static_randomStreaming_RandomStreamRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              randomStreaming.RandomStreamRequest.class, randomStreaming.RandomStreamRequest.Builder.class);
    }

    // Construct using randomStreaming.RandomStreamRequest.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bound_ = 0;

      count_ = 0;

      timeInterval_ = 0;

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return randomStreaming.RandomStreamingProto.internal_static_randomStreaming_RandomStreamRequest_descriptor;
    }

    @java.lang.Override
    public randomStreaming.RandomStreamRequest getDefaultInstanceForType() {
      return randomStreaming.RandomStreamRequest.getDefaultInstance();
    }

    @java.lang.Override
    public randomStreaming.RandomStreamRequest build() {
      randomStreaming.RandomStreamRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public randomStreaming.RandomStreamRequest buildPartial() {
      randomStreaming.RandomStreamRequest result = new randomStreaming.RandomStreamRequest(this);
      result.bound_ = bound_;
      result.count_ = count_;
      result.timeInterval_ = timeInterval_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof randomStreaming.RandomStreamRequest) {
        return mergeFrom((randomStreaming.RandomStreamRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(randomStreaming.RandomStreamRequest other) {
      if (other == randomStreaming.RandomStreamRequest.getDefaultInstance()) return this;
      if (other.getBound() != 0) {
        setBound(other.getBound());
      }
      if (other.getCount() != 0) {
        setCount(other.getCount());
      }
      if (other.getTimeInterval() != 0) {
        setTimeInterval(other.getTimeInterval());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      randomStreaming.RandomStreamRequest parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (randomStreaming.RandomStreamRequest) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private int bound_ ;
    /**
     * <code>int32 bound = 1;</code>
     * @return The bound.
     */
    @java.lang.Override
    public int getBound() {
      return bound_;
    }
    /**
     * <code>int32 bound = 1;</code>
     * @param value The bound to set.
     * @return This builder for chaining.
     */
    public Builder setBound(int value) {
      
      bound_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 bound = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearBound() {
      
      bound_ = 0;
      onChanged();
      return this;
    }

    private int count_ ;
    /**
     * <code>int32 count = 2;</code>
     * @return The count.
     */
    @java.lang.Override
    public int getCount() {
      return count_;
    }
    /**
     * <code>int32 count = 2;</code>
     * @param value The count to set.
     * @return This builder for chaining.
     */
    public Builder setCount(int value) {
      
      count_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 count = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearCount() {
      
      count_ = 0;
      onChanged();
      return this;
    }

    private int timeInterval_ ;
    /**
     * <code>int32 time_interval = 3;</code>
     * @return The timeInterval.
     */
    @java.lang.Override
    public int getTimeInterval() {
      return timeInterval_;
    }
    /**
     * <code>int32 time_interval = 3;</code>
     * @param value The timeInterval to set.
     * @return This builder for chaining.
     */
    public Builder setTimeInterval(int value) {
      
      timeInterval_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 time_interval = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearTimeInterval() {
      
      timeInterval_ = 0;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:randomStreaming.RandomStreamRequest)
  }

  // @@protoc_insertion_point(class_scope:randomStreaming.RandomStreamRequest)
  private static final randomStreaming.RandomStreamRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new randomStreaming.RandomStreamRequest();
  }

  public static randomStreaming.RandomStreamRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<RandomStreamRequest>
      PARSER = new com.google.protobuf.AbstractParser<RandomStreamRequest>() {
    @java.lang.Override
    public RandomStreamRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new RandomStreamRequest(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<RandomStreamRequest> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<RandomStreamRequest> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public randomStreaming.RandomStreamRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

