// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: randomstreaming.proto

package randomStreaming;

public interface RandomStreamRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:randomStreaming.RandomStreamRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 bound = 1;</code>
   * @return The bound.
   */
  int getBound();

  /**
   * <code>int32 count = 2;</code>
   * @return The count.
   */
  int getCount();

  /**
   * <code>int32 time_interval = 3;</code>
   * @return The timeInterval.
   */
  int getTimeInterval();
}
